docker-compose-yaml: docker-compose.yml

project: drupal9-example-simple

tasks:
  post-rollout:
    - run:
        name: drush deploy
        command: drush deploy
        service: cli

environments:
  main:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
