docker-compose-yaml: docker-compose.yml

project: drupal9-example-simple

tasks:
  post-rollout:
    # Enable once config sync has been setup.
    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    - run:
        name: drush deploy
        command: drush deploy
        service: cli

environments:
  main:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
