version: '3'

dotenv: ['.env']

vars:
  VERSION: '{{ .VERSION | default "latest"}}'
  REGISTRY: 'ghcr.io'
  IMAGE_CORE: '{{ .REGISTRY }}/{{ .ORG }}/php-7.4-cli-drupal-ddf-core:{{ .VERSION }}'

tasks:
  miktest:
    desc: Mikkel tester
    cmds:
      - echo {{ .CR_PAT }}
  ghcr:login:
    desc: Login into Github Container Registry
    cmds:
      - echo {{ .CR_PAT }} | docker login {{ .REGISTRY }} -u {{ .USERNAME }} --password-stdin
  core:image:build:
    desc: Build core image.
    deps: [ ghcr:login ]
    cmds:
      - docker build . -f core.dockerfile --tag {{ .IMAGE_CORE }}
  core:image:push:
    desc: Push core image to container registry.
    deps: [ ghcr:login ]
    cmds:
      - docker push {{ .IMAGE_CORE }}